#!/usr/bin/env node
/**
 * Build script: concatenates all L2 UI component files into mmo-ui.js
 * Usage: node ui/build.js
 * Run from: mmo/client_plugin/
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT  = path.join(ROOT, 'mmo-ui.js');

// Load order matters: core first, then layers that depend on them.
const FILES = [
    // Core (must be first — everything depends on L2_Theme and L2_Base)
    'ui/core/theme.js',
    'ui/core/input-blocker.js', // Must load before base.js
    'ui/core/base.js',

    // Layout
    'ui/layout/divider.js',
    'ui/layout/grid.js',
    'ui/layout/layout.js',
    'ui/layout/space.js',

    // Base
    'ui/base/button.js',
    'ui/base/icon.js',
    'ui/base/link.js',
    'ui/base/typography.js',

    // Navigation
    'ui/navigation/tabs.js',
    'ui/navigation/menu.js',
    'ui/navigation/dropdown.js',
    'ui/navigation/pagination.js',
    'ui/navigation/steps.js',
    'ui/navigation/breadcrumb.js',

    // Window
    'ui/window/subwindow.js',
    'ui/window/fullscreen.js',

    // Input
    'ui/input/input.js',
    'ui/input/input-number.js',
    'ui/input/select.js',
    'ui/input/checkbox.js',
    'ui/input/radio.js',
    'ui/input/switch.js',
    'ui/input/slider.js',
    'ui/input/textarea.js',

    // Data Display
    'ui/data/list.js',
    'ui/data/table.js',
    'ui/data/card.js',
    'ui/data/progress.js',
    'ui/data/tag.js',
    'ui/data/badge.js',
    'ui/data/avatar.js',
    'ui/data/collapse.js',
    'ui/data/tooltip.js',
    'ui/data/tree.js',
    'ui/data/statistic.js',
    'ui/data/empty.js',
    'ui/data/loading.js',
    'ui/data/chat-bubble.js',

    // Feedback / Message
    'ui/feedback/dialog.js',
    'ui/feedback/drawer.js',
    'ui/feedback/message.js',
    'ui/feedback/notification.js',
    'ui/feedback/alert.js',
    'ui/feedback/popconfirm.js',
];

const HEADER = `/*:
 * @plugindesc v2.0.0 MMO UI - Lineage 2 style canvas UI component library (DDD build).
 * @author MMO Framework
 *
 * Auto-generated by ui/build.js — DO NOT EDIT DIRECTLY.
 * Edit individual component files under ui/ and rebuild.
 *
 * Components (${FILES.length} files):
 *   Core:       L2_Theme, L2_Base
 *   Layout:     L2_Divider, L2_Grid, L2_Layout, L2_Space
 *   Base:       L2_Button, L2_Icon, L2_Link, L2_Typography
 *   Navigation: L2_Tabs, L2_Menu, L2_Dropdown, L2_Pagination, L2_Steps, L2_Breadcrumb
 *   Window:     L2_SubWindow, L2_FullscreenWindow
 *   Input:      L2_Input, L2_InputNumber, L2_Select, L2_Checkbox, L2_Radio, L2_Switch, L2_Slider, L2_Textarea
 *   Data:       L2_List, L2_Table, L2_Card, L2_Progress, L2_Tag, L2_Badge, L2_Avatar, L2_Collapse, L2_Tooltip, L2_Tree, L2_Statistic, L2_Empty, L2_Loading, L2_ChatBubble
 *   Feedback:   L2_Dialog, L2_Drawer, L2_Message, L2_Notification, L2_Alert, L2_Popconfirm
 */
`;

let output = HEADER + '\n';
let count = 0;

for (const relPath of FILES) {
    const absPath = path.join(ROOT, relPath);
    if (!fs.existsSync(absPath)) {
        console.error(`MISSING: ${relPath}`);
        process.exit(1);
    }
    const src = fs.readFileSync(absPath, 'utf8');
    output += `// ═══ ${relPath} ═══\n`;
    output += src.trim() + '\n\n';
    count++;
}

fs.writeFileSync(OUT, output, 'utf8');
const sizeKB = (Buffer.byteLength(output, 'utf8') / 1024).toFixed(1);
console.log(`Built ${OUT}`);
console.log(`  ${count} files, ${sizeKB} KB`);
